- name: Configurando o Webserver Nginx
  hosts: webservers
  become: true
  tasks:
    - name: Provisionando o WebServer Nginx
      apt: name=nginx update_cache=yes

- name: Executar script Python 
  hosts: webservers 
  become: true
  tasks: 
    - name: Executar o script Python 
      command: python3 /home/rodrigoafonso/devopspro/learn-terraform-aws-instance/ec2.py      