- name: Configurando o Webserver Nginx
  hosts: webservers
  become: true
  tasks:
    - name: Provisionando o WebServer Nginx
      apt: name=nginx update_cache=yes

- name: Executar script Python 
  hosts: webservers 
  become: true
  tasks: 

    - name: Definir permissão de execução para o script Python 
      file: 
        path: ../../ec2.py
        mode: '0755' 
        state: file

    - name: Executar o script Python 
      command: python3 ../../ec2.py      